server:
  servlet:
    session:
      timeout: 86400  # 3600(1시간) * 24 = 하루

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2test;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

logging:
  level:
    com.com.growth.community: debug
    org.springframework.security: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web.servlet: debug

api:
  coolsms:
    key: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}
    from: ${SMS_API_FROM}
