server:
  servlet:
    session:
      timeout: 86400  # 3600(1시간) * 24 = 하루

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2test;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  sql.init.mode: always


logging:
  level:
    com.com.growth.community: debug
    org.springframework.web.servlet: debug
    org.springframework.security: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace