server:
  servlet:
    session:
      timeout: 86400  # 3600(1시간) * 24 = 하루

spring:
  datasource:
    url: ${DATABASE_URL}
#    driver-class-name:
    username: ${DATABASE_USER}
    password: ${DATABASE_PW}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

logging:
  level:
    com.com.growth.community: debug
    org.springframework.web.servlet: debug
    org.springframework.security: error
    org.hibernate.type.descriptor.sql.BasicBinder: trace

springdoc:
  swagger-ui:
    enabled: false