spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/h2test;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false

logging:
  level:
    com.reivewer.codereivew: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace  #하이버네이트의 물음표 대신 실제 값 로그를 확인할 수 있다.